//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCar.DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCao
    {
        public int id { get; set; }
        public int tongSoXe { get; set; }
        public int soXeDaThue { get; set; }
        public int soxeConLai { get; set; }
        public decimal DoanThu { get; set; }
        public int soxeDangBaoTri { get; set; }
        public System.DateTime NgayBaoCao { get; set; }
        public decimal LoiNhuan { get; set; }
    }
}
