//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCar.DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoTri
    {
        public int Ma_BT { get; set; }
        public string SoXe { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public string LoaiDV { get; set; }
        public decimal chiphi { get; set; }
        public Nullable<System.DateTime> ngayKetThuc { get; set; }
    
        public virtual XEHOI XEHOI { get; set; }
    }
}
