//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCar.DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatTruoc
    {
        public int maDon { get; set; }
        public string MaXe { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime NgayNhanXe { get; set; }
        public System.DateTime NgayTra { get; set; }
        public Nullable<int> MaKH { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual XEHOI XEHOI { get; set; }
    }
}
