//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCar.DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }
    
        public int id { get; set; }
        public string Ten { get; set; }
        public string sdt { get; set; }
        public string mail { get; set; }
        public string iconString { get; set; }
        public string iconStringColor { get; set; }
        public string vitriCV { get; set; }
        public int soNamLV { get; set; }
        public Nullable<int> gioitinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
    }
}
