//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCar.DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThueXe
    {
        public int Ma_GD { get; set; }
        public int MaKhach { get; set; }
        public string SoXe { get; set; }
        public System.DateTime NgayThue { get; set; }
        public System.DateTime NgayTra { get; set; }
        public int songaythue { get; set; }
        public decimal chiphi { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual XEHOI XEHOI { get; set; }
    }
}
